execution.checkpointing.interval: 60s
blob.server.port: 6124
execution.checkpointing.mode: EXACTLY_ONCE
taskmanager.memory.process.size: 1600m
jobmanager.rpc.address: jobmanager
taskmanager.numberOfTaskSlots: 2
state.backend: rocksdb
state.savepoints.dir: file:///flink-data/savepoints
jobmanager.memory.process.size: 1600m
query.server.port: 6125
state.checkpoints.dir: file:///flink-data/checkpoints
