apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-job-config
  labels:
    app: flink
    component: jobmanager
    chart: {{ .Chart.Name }}
data:
  flink-job-config.yaml: |
    # Example config, replace with your actual YAML
    kafka:
      bootstrapServers: {{ .Values.job.kafkaBootstrap }}
      purchasesTopic: {{ .Values.job.purchasesTopic }}
      inventoriesTopic: {{ .Values.job.inventoriesTopic }}
      groupIdPrefix: {{ .Values.job.groupIdPrefix }}
    postgres:
      host: {{ .Values.job.pgHost }}
      port: {{ .Values.job.pgPort }}
      database: {{ .Values.job.pgDb }}
      user: {{ .Values.job.pgUser }}
      password: {{ .Values.job.pgPassword }}
      mergedTable: {{ .Values.job.mergedTable }}
    flink:
      checkpointIntervalMs: {{ .Values.job.checkpointInterval }}
      parallelism: {{ .Values.job.parallelism }}
