apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink.fullname" . }}-jobmanager
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: {{ include "flink.name" . }}
    component: jobmanager
